### ISSUE TITLE
Two exceptions from the app.sync() 

### ISSUE THREAD

**Issue by notmandatory** [bitcoindevkit/BDWallet#12]
@ethanasm found two exceptions from the bdk lib when calling app.sync() 

https://media.discordapp.net/attachments/754882831821570179/772879387069775872/Screen_Shot_2020-11-01_at_7.49.26_PM.png?width=1451&height=333

https://media.discordapp.net/attachments/754882831821570179/772879401402237018/Screen_Shot_2020-11-01_at_8.01.24_PM.png?width=1451&height=281

**Comment by notmandatory** [comment]
First error as text:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.bdwallet.app.regtest, PID: 19032
    java.lang.Exception: Cannot deserialize input: Error("expected `:`", line: 1, column: 10)
        at org.bitcoindevkit.bdkjni.Lib.sync(Lib.kt:72)
        at org.bdwallet.app.BDWApplication.sync(BDWApplication.kt:134)
        at org.bdwallet.app.ui.wallet.balance.BalanceViewModel$refreshSatBalance$3.invokeSuspend(BalanceViewModel.kt:126)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by notmandatory** [comment]
a different but related error in `bdkjni.Lib fun sync`:
```
E/BDKJNILIB: error = Cannot deserialize input: Error("control character (\\u0000-\\u001F) found while parsing a string", line: 1, column: 3)
    resString = {"error":"Cannot deserialize input: Error(\"control character (\\\\u0000-\\\\u001F) found while parsing a string\", line: 1, column: 3)","code":-1003}
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.bdwallet.app.regtest, PID: 24295
    java.lang.Exception: Cannot deserialize input: Error("control character (\\u0000-\\u001F) found while parsing a string", line: 1, column: 3)
        at org.bitcoindevkit.bdkjni.Lib.sync(Lib.kt:79)
        at org.bdwallet.app.BDWApplication.sync(BDWApplication.kt:134)
        at org.bdwallet.app.ui.wallet.balance.BalanceViewModel$refreshSatBalance$3.invokeSuspend(BalanceViewModel.kt:129)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
```

**Comment by notmandatory** [comment]
This error seems to be a memory issue going between the JVM and native library.. data getting lost when multiple threads accessing the `bdk` call function. I have a way to segregate lib access on the same thread to avoids contention and I'm also adding some better error handing.

Long term we may need to change how the `bdk` lib is accessed from the JVM, but for now kotlin coroutines can be told to run in the same thread for background work and I'm triggering refreshes from a ticker rather than via the UI which also is safer.
